  
name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Startup
      run: echo Building a Plugin
    - name: Build
      run: |
        echo Building...
        chmod +x Build/BuildScript.php
        php -dphar.readonly=0 Build/BuildScript.php --make . --out Build/ReplayProtocol.phar
        echo Build completed!
    - name: Upload to release
      uses: JasonEtco/upload-to-release@master
      with:
        args: Build/ReplayProtocol.phar application/x-gzip
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        
