  
name: CI

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Startup
      run: echo Building a Plugin
    - name: Build
      run: echo ${{ github.sha }} > Release.txt
    - name: Build
      run: |
        echo Building...
        chmod +x Build/BuildScript.php
        php -dphar.readonly=0 Build/BuildScript.php --make . --out ReplayProtocol.phar
        echo Build completed!
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'master')
      with:
        files: Release.txt
        draft: false
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

        
